[package]
name = "qalam"
authors.workspace = true
edition.workspace = true
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lib]
required-features = ["default"]

[features]
default = ["uuid", "libp2p", "derive_more", "tokio", "hex"]

derive_more = ["derive_more/debug"]
hex = ["hex/alloc"]
libp2p = [
  "libp2p/macros",
  "libp2p/mdns",
  "libp2p/tokio",
  "libp2p/gossipsub",
  "libp2p/tcp",
  "libp2p/noise",
  "libp2p/yamux",
]
tokio = ["tokio/sync"]
uuid = ["uuid/v7"]

[dependencies]
derive_more = { version = "2.1.1", default-features = false }
futures-util = { version = "0.3.32", default-features = false }
hex = { version = "0.4.3", default-features = false }
libp2p = { version = "0.56.0", default-features = false }
sha2 = { version = "0.11.0", default-features = false }
tokio = { version = "1.52.3", default-features = false }
tracing = { version = "0.1.44", default-features = false }
uuid = { version = "1", default-features = false }

[lints]
workspace = true
