[package]
name = "qalam"

authors = ["Alibek<freed.alibek@gmail.com>"]

edition = "2024"
version = "0.1.0"

description = ""
# keywords = []
# categories = []

# homepage = ""
repository = "https://github.com/lolp1ke/qara"
# documentation = ""
readme = "README.md"
license-file = "LICENSE-APACHE"

# include = []
# exclude = []

rust-version = "1.94.0"

[lib]
required-features = ["default"]

[features]
default = ["uuid", "libp2p", "derive_more", "tokio", "hex"]

derive_more = ["derive_more/debug"]
hex = ["hex/alloc"]
libp2p = [
  "libp2p/macros",
  "libp2p/mdns",
  "libp2p/tokio",
  "libp2p/gossipsub",
  "libp2p/tcp",
  "libp2p/noise",
  "libp2p/yamux",
]
tokio = ["tokio/sync", "tokio/macros"]
uuid = ["uuid/std", "uuid/v7"]

[dependencies]
anyhow = { version = "1.0.102", default-features = false }
derive_more = { version = "2.1.1", default-features = false }
futures-util = { version = "0.3.32", default-features = false }
hex = { version = "0.4.3", default-features = false }
libp2p = { version = "0.56.0", default-features = false }
sha2 = { version = "0.11.0", default-features = false }
tokio = { version = "1.52.3", default-features = false }
tracing = { version = "0.1.44", default-features = false }
uuid = { version = "1", default-features = false }

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
